### ISSUE TITLE
Confusion over which CMSSW version to use while creating ticket

### ISSUE THREAD

**Issue by pkalbhor** [cms-AlCaDB/AlCaVal#22]
While creating new ticket, CMSSW release is mandatory. 
![image](https://user-images.githubusercontent.com/30353865/201519010-3eee1c07-8aec-42ee-be90-78ed3d185638.png)

AlCa contacts often get confused over which cmssw release to use. Sometime they end up putting older release which no one can edit once ticket is created.
Suggestion is that, we should auto-fill this field with latest stable release. One can fetch list of releases from here: https://api.github.com/repos/cms-sw/cmssw/releases
So when someone tries to create new ticket, he/she should see that `CMSSW Release` field is already filled with latest stable release.

**Comment by tvami** [comment]
it should be taken from the T0 API. For example now we are in 12_6_X for the master release that https://api.github.com/repos/cms-sw/cmssw/releases would point to, but we use the 12_4_X release cycle.

**Comment by pkalbhor** [comment]
Thanks Tamas for pointing that out. I think this is good first issue for Matheus to work on. @teteumac

**Comment by tvami** [comment]
@teteumac you can take inspiration from the MRH:
 
You get the T0 API here
https://gitlab.cern.ch/cms-ppdweb/cmsDbMultiRunHarvesting/-/blob/master/backend/python/dataDiscovery/discover.py#L10
and
https://gitlab.cern.ch/cms-ppdweb/cmsDbMultiRunHarvesting/-/blob/master/backend/python/dataDiscovery/discover.py#L493

and the T0 config `t0config` is loaded here
https://gitlab.cern.ch/cms-ppdweb/cmsDbMultiRunHarvesting/-/blob/master/backend/python/dataDiscovery/discover.py#L540
you get the CMSSW by doing
```
`cmssw=t0config['cmssw'],`
```

and that's all

**Comment by pkalbhor** [comment]
Feature implemented by Matheus in this PR #32 . Closing this issue
