### ISSUE TITLE
RunWhiteList issue when individual runs are passed to the relval

### ISSUE THREAD

**Issue by pkalbhor** [cms-AlCaDB/AlCaVal#31]
When list of runs passed in RelVal from Runs (runs) field, we are facing issue in processing the workflow. Basically, they are failing when submitted.
**What issue?** :
Job dictionary (to be used by Request Manager) is getting faulty parameter.
RunWhiteList key from _job_dict_ should be of type **list of runs in integer form**. Instead, wrongly we are passing list of runs in string form.
Here is example of faulty _job_dict_:
https://alcaval.web.cern.ch/api/relvals/get_dict/CMSSW_12_4_11_patch3__TSG-HLTNew-EphemeralHLTPhysics1Run2022G-00002

**Comment by teteumac** [comment]
I believe that the error may be in these two parts of the code. 

https://github.com/cms-AlCaDB/AlCaVal/blob/98152e0c6afa36ef37e5da5f82d3ff3a44aeb1e8/api/controller/relval_controller.py#L270 [1]

https://github.com/cms-AlCaDB/AlCaVal/blob/98152e0c6afa36ef37e5da5f82d3ff3a44aeb1e8/api/controller/relval_controller.py#L407 [2]

I suggest trying to assign the job_dict list the following line:

To [1] 

`task_dict['RunWhitelist'] = [int(run) for run in input_dict['run']] `

and [2] 

`job_dict['RunWhitelist'] = [int(run) for run in input_dict['run']]`

I would like to know your opinion.

**Comment by pkalbhor** [comment]
Hi @teteumac ,
I would suggest you to test sample submission from your dev instance. We have two types of input runs: one coming from LS range e.g. `{365118: [[1,100]]}`  and other from list or runs e.g. `365118, 365119`
We have issue with second type of submission. 
I suggest create two workflow for each type of the input run and submit it for processing as test

FYI: @tvami , @francescobrivio, @saumyaphor4252

**Comment by teteumac** [comment]
Yes Pritam. I forgot to remove this message because I thought I wouldn't be able to solve both problems on the same day, but I managed to deliver, they were very fast, I didn't have too many difficulties. I still don't know how to do these tests in my development instance, that is, what kind of datasets should I consider, machine configurations, or other fields that need to be filled in the ticket.

**Comment by pkalbhor** [comment]
One ticket can be copy of any one of the current ticket where we have been providing run numbers in JSON format. 
Other ticket should be with run number provided as it is. e.g. `365118, 365119`
Open localhost:8080 from browser which is called local instance. You can open it after running `docker compose up -d`
I had shown you the demo if you remember.
On this local instance you can submit these two relvals as REAL submission. 
Hope this helps

**Comment by pkalbhor** [comment]
Anyway, I am create a ticket for this test. 
https://alcaval.web.cern.ch/tickets?prepid=CMSSW_13_0_0__TestSubmission-00001

**Comment by pkalbhor** [comment]
It is tested successfully:
https://alcaval.web.cern.ch/relvals?prepid=CMSSW_13_0_0__TestSubmission-*&status=submitted&shown=11111100000000000101&limit=50&page=0&filter=
Hence closing the issue. 

Cheers,
