### ISSUE TITLE
Block job submission in case of failure of the local test

### ISSUE THREAD

**Issue by francescobrivio** [cms-AlCaDB/AlCaVal#35]
It was recently noticed that jobs can be submitted even if the local tests are crashing, see for example:
 - https://alcaval.web.cern.ch/relvals/local_test_result/CMSSW_13_0_6__PPS-PromptNew-AlCaPPSPromptRun2023C-00001

which failed, it was not noticed, and lead to 0% events produced in production:
- https://cms-pdmv.cern.ch/stats/?prepid=CMSSW_13_0_6__PPS-PromptNew-AlCaPPSPromptRun2023C-00001

This should be avoided and the submission of jobs should be "blocked" in case the local tests are failing.

**Comment by tvami** [comment]
Duplicate issue
