### ISSUE TITLE
Fix SMTP mail sender

### ISSUE THREAD

**Issue by francescobrivio** [cms-AlCaDB/AlCaVal#37]
As of two days ago (28 June 2023) the SMTP service is no longer supported:
- https://cern.service-now.com/service-portal?id=outage&n=OTG0077695

and we use it in `core_lib/utils/emailer.py`

The poposed options (IIUC) are:
 - remove the basic authentication to smtp.cern.ch and update it to an Oath based authentication to the new smtp server like in this sample https://gitlab.cern.ch/mail/mailservices-code-samples/-/tree/master/Python/oauth2-samples/oauth2_smtp
 - use cernmx.cern.ch port 25 anonymous auth (no auth)

The second option was implemented in the ConddbBrowser in:
- https://gitlab.cern.ch/cms-ppdweb/cmsDbBrowser/-/merge_requests/198/diffs

We should do the same here probably.

**Comment by tvami** [comment]
@saumyaphor4252 you merged this in dev right?
https://github.com/cms-AlCaDB/AlCaVal/pull/40
But what about in prod?

**Comment by saumyaphor4252** [comment]
Nope, it's merged in both Dev and Prod. Prod is here https://github.com/cms-AlCaDB/AlCaVal/pull/40.

**Comment by tvami** [comment]
Awesome, this can be closed then?
